import type { NextPage } from 'next'
import Head from 'next/head'
import { Player } from '@livepeer/react';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <Player
          title='underground tunnel'
          src="ipfs://QmXuofDQsGf8bpkLMw4UKuxnB7pScBocUirYY1U3z6ApJH"
          autoUrlUpload={{ fallback: true, ipfsGateway: 'https://gateway.pinata.cloud' }}
          theme={{
            colors: {
              accent: '#00a55f',
            },
            space: {
              controlsBottomMarginX: '10px',
              controlsBottomMarginY: '5px',
              controlsTopMarginX: '15px',
              controlsTopMarginY: '10px',
            },
            radii: {
              containerBorderRadius: '0px',
            },
          }}
        />
      </main>
    </div>
  )
}

export default Home
